services:
  vault:
    image: hashicorp/vault:1.15.2
    container_name: vault-dev
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - ./vault-config:/vault/config
    command: ["vault", "server", "-dev", "-dev-root-token-id=myroot"]
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - vault-network

  # Vault UI (선택사항 - 웹 UI 접근용)
  vault-ui:
    image: djenriquez/vault-ui:latest
    container_name: vault-ui
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      VAULT_URL_DEFAULT: http://vault:8200
      VAULT_AUTH_DEFAULT: TOKEN
    depends_on:
      vault:
        condition: service_healthy
    networks:
      - vault-network

volumes:
  vault-data:
    driver: local
  vault-logs:
    driver: local

networks:
  vault-network:
    driver: bridge
